// web/src/lib/components/LoadingSpinner.svelte
<!-- web/src/lib/components/LoadingSpinner.svelte -->
<script>
  let {
    size = 'medium',
    message = '',
    overlay = false,
    color = 'primary'
  } = $props();

  let sizeClasses = $derived({
    small: 'w-4 h-4 border-2',
    medium: 'w-8 h-8 border-3',
    large: 'w-12 h-12 border-4'
  }[size] || 'w-8 h-8 border-3');

  let colorClasses = $derived({
    primary: 'border-blue-600 border-t-transparent',
    white: 'border-white border-t-transparent',
    gray: 'border-gray-600 border-t-transparent'
  }[color] || 'border-blue-600 border-t-transparent');
</script>

{#if overlay}
  <div class="loading-overlay">
    <div class="loading-content">
      <div class="spinner {sizeClasses} {colorClasses}"></div>
      {#if message}
        <p class="loading-message">{message}</p>
      {/if}
    </div>
  </div>
{:else}
  <div class="loading-container">
    <div class="spinner {sizeClasses} {colorClasses}"></div>
    {#if message}
      <p class="loading-message">{message}</p>
    {/if}
  </div>
{/if}

<style>
  .loading-overlay {
    position: fixed;
    inset: 0;
    background: rgba(255, 255, 255, 0.9);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000;
  }

  .loading-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 1rem;
    padding: 2rem;
  }

  .loading-content {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
  }

  .spinner {
    border-style: solid;
    border-radius: 50%;
    animation: spin 1s linear infinite;
  }

  .loading-message {
    margin: 0;
    font-size: 0.875rem;
    color: var(--text-secondary, #6b7280);
    text-align: center;
  }

  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }

  /* Border width utilities */
  .border-2 {
    border-width: 2px;
  }

  .border-3 {
    border-width: 3px;
  }

  .border-4 {
    border-width: 4px;
  }

  /* Size utilities */
  .w-4 { width: 1rem; }
  .h-4 { height: 1rem; }
  .w-8 { width: 2rem; }
  .h-8 { height: 2rem; }
  .w-12 { width: 3rem; }
  .h-12 { height: 3rem; }
</style>

// frontend/src/components/common/LoadingSpinner.jsx
// frontend/src/components/common/LoadingSpinner.jsx
// Reusable loading spinner component - fully functional implementation

import React from 'react';
import { motion } from 'framer-motion';

const LoadingSpinner = ({
                          size = 'medium',
                          message = 'Loading...',
                          showMessage = true,
                          color = 'blue',
                          className = '',
                          fullScreen = false
                        }) => {
  // Size configurations
  const sizeClasses = {
    small: 'w-4 h-4',
    medium: 'w-8 h-8',
    large: 'w-12 h-12',
    xlarge: 'w-16 h-16'
  };

  const textSizeClasses = {
    small: 'text-xs',
    medium: 'text-sm',
    large: 'text-base',
    xlarge: 'text-lg'
  };

  // Color configurations
  const colorClasses = {
    blue: 'border-blue-600',
    gray: 'border-gray-600',
    green: 'border-green-600',
    red: 'border-red-600',
    yellow: 'border-yellow-600',
    purple: 'border-purple-600',
    indigo: 'border-indigo-600'
  };

  const textColorClasses = {
    blue: 'text-blue-600',
    gray: 'text-gray-600',
    green: 'text-green-600',
    red: 'text-red-600',
    yellow: 'text-yellow-600',
    purple: 'text-purple-600',
    indigo: 'text-indigo-600'
  };

  const spinnerElement = (
      <motion.div
          animate={{ rotate: 360 }}
          transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
          className={`
        ${sizeClasses[size]} 
        border-4 
        ${colorClasses[color]} 
        border-t-transparent 
        rounded-full
        ${className}
      `}
      />
  );

  const content = (
      <div className={`flex flex-col items-center justify-center gap-3 ${fullScreen ? 'min-h-screen' : ''}`}>
        {spinnerElement}
        {showMessage && message && (
            <motion.p
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.2 }}
                className={`${textSizeClasses[size]} ${textColorClasses[color]} font-medium`}
            >
              {message}
            </motion.p>
        )}
      </div>
  );

  if (fullScreen) {
    return (
        <div className="fixed inset-0 bg-white bg-opacity-75 backdrop-blur-sm flex items-center justify-center z-50">
          {content}
        </div>
    );
  }

  return content;
};

export default LoadingSpinner;
