// frontend/src/components/configurator/PricingDisplay.jsx
import React, { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  CurrencyDollarIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  InformationCircleIcon,
  TagIcon,
  // TrendingUpIcon,
  // TrendingDownIcon,
  CheckCircleIcon,
  ExclamationTriangleIcon,
} from '@heroicons/react/24/outline';

const PricingDisplay = ({
  pricing = { totalPrice: 0, breakdown: [] },
  isValid = true,
  isLoading = false,
  showBreakdown = true,
  showVolumeDiscounts = true,
  showComparison = false,
  comparisonPrice = null,
  currency = 'USD',
  showTax = false,
  taxRate = 0.08,
}) => {
  const [isExpanded, setIsExpanded] = useState(false);
  const [selectedTier, setSelectedTier] = useState(null);

  // Calculate derived values
  const subtotal = useMemo(() => {
    return pricing.breakdown?.reduce((sum, item) => sum + (item.totalPrice || 0), 0) || pricing.totalPrice || 0;
  }, [pricing]);

  const taxAmount = useMemo(() => {
    return showTax ? subtotal * taxRate : 0;
  }, [subtotal, taxRate, showTax]);

  const totalWithTax = useMemo(() => {
    return subtotal + taxAmount;
  }, [subtotal, taxAmount]);

  const savings = useMemo(() => {
    if (!comparisonPrice || !showComparison) return 0;
    return Math.max(0, comparisonPrice - totalWithTax);
  }, [comparisonPrice, totalWithTax, showComparison]);

  const savingsPercentage = useMemo(() => {
    if (!savings || !comparisonPrice) return 0;
    return (savings / comparisonPrice) * 100;
  }, [savings, comparisonPrice]);

  // Format currency
  const formatCurrency = (amount, options = {}) => {
    const { showSymbol = true, showDecimals = true } = options;
    
    if (amount === 0) return showSymbol ? '$0' : '0';
    
    const formatted = new Intl.NumberFormat('en-US', {
      style: showSymbol ? 'currency' : 'decimal',
      currency: currency,
      minimumFractionDigits: showDecimals ? 2 : 0,
      maximumFractionDigits: showDecimals ? 2 : 0,
    }).format(amount);
    
    return formatted;
  };

  // Group breakdown items by category
  const groupedBreakdown = useMemo(() => {
    if (!pricing.breakdown) return [];
    
    const groups = pricing.breakdown.reduce((acc, item) => {
      const category = item.category || 'Configuration';
      if (!acc[category]) {
        acc[category] = [];
      }
      acc[category].push(item);
      return acc;
    }, {});
    
    return Object.entries(groups).map(([category, items]) => ({
      category,
      items,
      total: items.reduce((sum, item) => sum + (item.totalPrice || 0), 0),
    }));
  }, [pricing.breakdown]);

  // Volume discount tiers (demo data)
  const volumeDiscounts = useMemo(() => {
    if (!showVolumeDiscounts) return [];
    
    return [
      { quantity: 1, discount: 0, label: 'Single Unit' },
      { quantity: 5, discount: 0.05, label: '5+ Units' },
      { quantity: 10, discount: 0.10, label: '10+ Units' },
      { quantity: 25, discount: 0.15, label: '25+ Units' },
    ];
  }, [showVolumeDiscounts]);

  return (
    <div className="bg-white rounded-lg shadow-sm border border-gray-200">
      {/* Header */}
      <div className="p-6 border-b border-gray-200">
        <div className="flex items-center justify-between">
          <div className="flex items-center">
            <CurrencyDollarIcon className="h-6 w-6 text-green-600 mr-2" />
            <h3 className="text-lg font-semibold text-gray-900">Pricing</h3>
          </div>
          
          {/* Status Indicator */}
          <div className="flex items-center">
            {isValid ? (
              <div className="flex items-center text-green-600">
                <CheckCircleIcon className="h-5 w-5 mr-1" />
                <span className="text-sm font-medium">Valid</span>
              </div>
            ) : (
              <div className="flex items-center text-red-600">
                <ExclamationTriangleIcon className="h-5 w-5 mr-1" />
                <span className="text-sm font-medium">Invalid</span>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Main Pricing */}
      <div className="p-6">
        {/* Total Price */}
        <motion.div
          initial={{ scale: 0.95, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          className="text-center mb-6"
        >
          <div className="text-3xl font-bold text-gray-900 mb-2">
            {isLoading ? (
              <div className="animate-pulse bg-gray-200 h-8 w-32 mx-auto rounded" />
            ) : (
              formatCurrency(totalWithTax)
            )}
          </div>
          
          {showTax && taxAmount > 0 && (
            <p className="text-sm text-gray-600">
              Includes {formatCurrency(taxAmount)} tax ({(taxRate * 100).toFixed(1)}%)
            </p>
          )}

          {/* Comparison and Savings */}
          {showComparison && comparisonPrice && !isLoading && (
            <div className="mt-3 space-y-1">
              <div className="text-sm text-gray-500 line-through">
                Was: {formatCurrency(comparisonPrice)}
              </div>
              {savings > 0 && (
                <div className="flex items-center justify-center text-green-600">
                  <span className="text-sm font-medium">
                    Save {formatCurrency(savings)} ({savingsPercentage.toFixed(0)}% off)
                  </span>
                </div>
              )}
            </div>
          )}
        </motion.div>

        {/* Volume Discounts */}
        {showVolumeDiscounts && volumeDiscounts.length > 0 && !isLoading && (
          <div className="mb-6">
            <h4 className="text-sm font-medium text-gray-900 mb-3 flex items-center">
              <TagIcon className="h-4 w-4 mr-1" />
              Volume Discounts
            </h4>
            <div className="grid grid-cols-2 gap-2">
              {volumeDiscounts.map((tier, index) => {
                const discountedPrice = totalWithTax * (1 - tier.discount);
                const isSelected = selectedTier === index;
                
                return (
                  <button
                    key={tier.quantity}
                    onClick={() => setSelectedTier(isSelected ? null : index)}
                    className={`p-3 rounded-lg border text-left transition-all ${
                      isSelected
                        ? 'border-blue-500 bg-blue-50'
                        : 'border-gray-200 hover:border-gray-300'
                    }`}
                  >
                    <div className="text-sm font-medium text-gray-900">
                      {tier.label}
                    </div>
                    <div className="text-lg font-bold text-green-600">
                      {formatCurrency(discountedPrice)}
                    </div>
                    {tier.discount > 0 && (
                      <div className="text-xs text-green-600">
                        {(tier.discount * 100).toFixed(0)}% off
                      </div>
                    )}
                  </button>
                );
              })}
            </div>
          </div>
        )}

        {/* Breakdown Toggle */}
        {showBreakdown && pricing.breakdown && pricing.breakdown.length > 0 && (
          <div className="border-t border-gray-200 pt-4">
            <button
              onClick={() => setIsExpanded(!isExpanded)}
              className="w-full flex items-center justify-between text-sm font-medium text-gray-700 hover:text-gray-900 transition-colors"
            >
              <span>Price Breakdown</span>
              {isExpanded ? (
                <ChevronUpIcon className="h-4 w-4" />
              ) : (
                <ChevronDownIcon className="h-4 w-4" />
              )}
            </button>

            <AnimatePresence>
              {isExpanded && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  className="mt-4 space-y-4 overflow-hidden"
                >
                  {groupedBreakdown.map((group, groupIndex) => (
                    <div key={group.category} className="space-y-2">
                      <h5 className="text-sm font-medium text-gray-900 border-b border-gray-100 pb-1">
                        {group.category}
                      </h5>
                      
                      {group.items.map((item, itemIndex) => (
                        <motion.div
                          key={`${item.id || itemIndex}`}
                          initial={{ opacity: 0, x: -10 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: (groupIndex * group.items.length + itemIndex) * 0.05 }}
                          className="flex items-center justify-between py-2 px-3 bg-gray-50 rounded text-sm"
                        >
                          <div className="flex-1">
                            <div className="font-medium text-gray-900">
                              {item.name}
                            </div>
                            {item.description && (
                              <div className="text-gray-600 text-xs mt-1">
                                {item.description}
                              </div>
                            )}
                            {item.quantity && item.quantity > 1 && (
                              <div className="text-gray-500 text-xs">
                                Qty: {item.quantity} × {formatCurrency(item.unitPrice || 0)}
                              </div>
                            )}
                          </div>
                          
                          <div className="text-right ml-4">
                            <div className="font-semibold text-gray-900">
                              {formatCurrency(item.totalPrice || 0)}
                            </div>
                            {item.discount && item.discount > 0 && (
                              <div className="text-xs text-green-600">
                                -{(item.discount * 100).toFixed(0)}% discount
                              </div>
                            )}
                          </div>
                        </motion.div>
                      ))}
                      
                      {/* Group Subtotal */}
                      <div className="flex justify-between items-center pt-2 border-t border-gray-200 text-sm">
                        <span className="font-medium text-gray-700">
                          {group.category} Subtotal:
                        </span>
                        <span className="font-semibold text-gray-900">
                          {formatCurrency(group.total)}
                        </span>
                      </div>
                    </div>
                  ))}

                  {/* Totals Summary */}
                  <div className="border-t border-gray-200 pt-4 space-y-2">
                    <div className="flex justify-between items-center text-sm">
                      <span className="text-gray-600">Subtotal:</span>
                      <span className="font-medium text-gray-900">
                        {formatCurrency(subtotal)}
                      </span>
                    </div>
                    
                    {showTax && taxAmount > 0 && (
                      <div className="flex justify-between items-center text-sm">
                        <span className="text-gray-600">
                          Tax ({(taxRate * 100).toFixed(1)}%):
                        </span>
                        <span className="font-medium text-gray-900">
                          {formatCurrency(taxAmount)}
                        </span>
                      </div>
                    )}
                    
                    <div className="flex justify-between items-center text-base font-semibold text-gray-900 border-t border-gray-200 pt-2">
                      <span>Total:</span>
                      <span>{formatCurrency(totalWithTax)}</span>
                    </div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        )}

        {/* Empty State */}
        {(!pricing.breakdown || pricing.breakdown.length === 0) && subtotal === 0 && !isLoading && (
          <div className="text-center py-8 text-gray-500">
            <CurrencyDollarIcon className="h-12 w-12 mx-auto mb-3 text-gray-300" />
            <p className="text-sm">No selections made yet</p>
            <p className="text-xs mt-1">Add options to see pricing</p>
          </div>
        )}

        {/* Loading State */}
        {isLoading && (
          <div className="space-y-3">
            <div className="animate-pulse">
              <div className="h-4 bg-gray-200 rounded w-3/4 mb-2" />
              <div className="h-4 bg-gray-200 rounded w-1/2 mb-2" />
              <div className="h-4 bg-gray-200 rounded w-5/6" />
            </div>
          </div>
        )}

        {/* Invalid Configuration Warning */}
        {!isValid && !isLoading && (
          <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-lg">
            <div className="flex items-center">
              <ExclamationTriangleIcon className="h-5 w-5 text-red-400 mr-2" />
              <div>
                <p className="text-sm font-medium text-red-800">
                  Invalid Configuration
                </p>
                <p className="text-sm text-red-600 mt-1">
                  Please resolve constraint violations before proceeding.
                </p>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default PricingDisplay;

// web/src/lib/components/PricingDisplay.svelte
<!-- web/src/lib/components/PricingDisplay.svelte -->
<script>
  let {
    pricingData,
    selections = {},
    options = [],
    volumeTiers = [],
    detailed = false
  } = $props();

  let showBreakdown = $state(detailed);
  let showDiscounts = $state(true);

  // Get option details for pricing display
  function getOption(optionId) {
    if (!Array.isArray(options)) return null;
    return options.find(o => o.id === optionId);
  }

  // Format currency
  function formatPrice(amount) {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD'
    }).format(amount || 0);
  }

  // Calculate savings
  let totalSavings = $derived(() => {
    if (!pricingData?.discounts) return 0;
    return pricingData.discounts.reduce((sum, d) => sum + (d.amount || 0), 0);
  });

  let savingsPercent = $derived(() => {
    if (!pricingData || !totalSavings) return 0;
    const subtotal = pricingData.base_price + (pricingData.options_total || 0);
    if (subtotal === 0) return 0;
    return Math.round((totalSavings / subtotal) * 100);
  });

  // Group selections by option group
  let groupedSelections = $derived(() => {
    const groups = new Map();

    Object.entries(selections).forEach(([optionId, quantity]) => {
      if (quantity <= 0) return;

      const option = getOption(optionId);
      if (!option) return;

      const groupId = option.group_id || 'other';
      if (!groups.has(groupId)) {
        groups.set(groupId, []);
      }

      groups.get(groupId).push({
        option,
        quantity,
        lineTotal: (option.price || 0) * quantity
      });
    });

    return Array.from(groups.entries());
  });
</script>

<div class="pricing-display" class:detailed>
  {#if !pricingData}
    <div class="pricing-empty">
      <p>Add options to see pricing</p>
    </div>
  {:else}
    <!-- Summary Section -->
    <div class="pricing-summary">
      <div class="summary-row total">
        <span class="label">Total Price</span>
        <span class="amount">{formatPrice(pricingData.total_price)}</span>
      </div>

      {#if totalSavings > 0}
        <div class="summary-row savings">
          <span class="label">Total Savings</span>
          <span class="amount">-{formatPrice(totalSavings)} ({savingsPercent}%)</span>
        </div>
      {/if}

      {#if detailed}
        <button
                class="toggle-btn"
                onclick={() => showBreakdown = !showBreakdown}
        >
          {showBreakdown ? 'Hide' : 'Show'} Breakdown
          <svg class="chevron" class:rotated={showBreakdown} width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
            <path d="M4.646 6.646a.5.5 0 01.708 0L8 9.293l2.646-2.647a.5.5 0 01.708.708l-3 3a.5.5 0 01-.708 0l-3-3a.5.5 0 010-.708z"/>
          </svg>
        </button>
      {/if}
    </div>

    {#if showBreakdown}
      <!-- Base Price -->
      <div class="pricing-section">
        <h4 class="section-title">Base Configuration</h4>
        <div class="line-item">
          <span class="item-name">Base Model Price</span>
          <span class="item-price">{formatPrice(pricingData.base_price)}</span>
        </div>
      </div>

      <!-- Selected Options -->
      {#if groupedSelections.length > 0}
        <div class="pricing-section">
          <h4 class="section-title">Selected Options</h4>
          {#each groupedSelections as [groupId, items]}
            <div class="option-group">
              {#each items as { option, quantity, lineTotal }}
                <div class="line-item">
                  <div class="item-details">
                    <span class="item-name">{option.name}</span>
                    {#if quantity > 1}
                      <span class="item-quantity">×{quantity} @ {formatPrice(option.price)} each</span>
                    {/if}
                  </div>
                  <span class="item-price">{formatPrice(lineTotal)}</span>
                </div>
              {/each}
            </div>
          {/each}

          <div class="line-item subtotal">
            <span class="item-name">Options Subtotal</span>
            <span class="item-price">{formatPrice(pricingData.options_total || 0)}</span>
          </div>
        </div>
      {/if}

      <!-- Discounts -->
      {#if pricingData.discounts?.length > 0}
        <div class="pricing-section">
          <h4 class="section-title">
            Discounts Applied
            <button
                    class="toggle-discounts"
                    onclick={() => showDiscounts = !showDiscounts}
            >
              {showDiscounts ? 'Hide' : 'Show'}
            </button>
          </h4>

          {#if showDiscounts}
            {#each pricingData.discounts as discount}
              <div class="line-item discount">
                <div class="item-details">
                  <span class="item-name">{discount.name}</span>
                  {#if discount.description}
                    <span class="item-description">{discount.description}</span>
                  {/if}
                </div>
                <span class="item-price discount-amount">-{formatPrice(discount.amount)}</span>
              </div>
            {/each}
          {/if}
        </div>
      {/if}

      <!-- Volume Tiers -->
      {#if volumeTiers.length > 0 && detailed}
        <div class="pricing-section">
          <h4 class="section-title">Volume Pricing Tiers</h4>
          <div class="volume-tiers">
            {#each volumeTiers as tier}
              {@const isActive = pricingData.active_tier?.id === tier.id}
              <div class="tier-item" class:active={isActive}>
                <div class="tier-range">
                  {tier.min_quantity}
                  {#if tier.max_quantity}
                    - {tier.max_quantity}
                  {:else}
                    +
                  {/if}
                  units
                </div>
                <div class="tier-discount">
                  {tier.discount_percent}% off
                  {#if isActive}
                    <span class="active-badge">Active</span>
                  {/if}
                </div>
              </div>
            {/each}
          </div>
        </div>
      {/if}

      <!-- Price Breakdown -->
      {#if pricingData.breakdown && detailed}
        <div class="pricing-section">
          <h4 class="section-title">Detailed Breakdown</h4>
          <div class="breakdown-items">
            {#each pricingData.breakdown as item}
              <div class="line-item small">
                <span class="item-name">{item.name}</span>
                <span class="item-price">{formatPrice(item.amount)}</span>
              </div>
            {/each}
          </div>
        </div>
      {/if}
    {/if}

    <!-- Final Total -->
    <div class="pricing-footer">
      <div class="final-total">
        <span class="label">Total</span>
        <span class="amount">{formatPrice(pricingData.total_price)}</span>
      </div>

      {#if pricingData.currency && pricingData.currency !== 'USD'}
        <div class="currency-note">
          Prices shown in {pricingData.currency}
        </div>
      {/if}
    </div>
  {/if}
</div>

<style>
  .pricing-display {
    background: var(--bg-primary, #ffffff);
    border: 1px solid var(--border-color, #e5e7eb);
    border-radius: 8px;
    overflow: hidden;
  }

  .pricing-display.detailed {
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
  }

  .pricing-empty {
    padding: 3rem;
    text-align: center;
    color: var(--text-secondary, #6b7280);
  }

  .pricing-summary {
    padding: 1.5rem;
    background: var(--bg-secondary, #f9fafb);
    border-bottom: 1px solid var(--border-color, #e5e7eb);
  }

  .summary-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 0.75rem;
  }

  .summary-row:last-child {
    margin-bottom: 0;
  }

  .summary-row.total {
    font-size: 1.25rem;
    font-weight: 700;
    color: var(--text-primary, #111827);
  }

  .summary-row.savings {
    color: var(--success-color, #10b981);
    font-weight: 600;
  }

  .toggle-btn {
    margin-top: 1rem;
    padding: 0.5rem 1rem;
    width: 100%;
    background: var(--bg-primary, #ffffff);
    border: 1px solid var(--border-color, #e5e7eb);
    border-radius: 6px;
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    transition: all 0.2s;
  }

  .toggle-btn:hover {
    background: var(--bg-tertiary, #f3f4f6);
  }

  .chevron {
    transition: transform 0.2s;
  }

  .chevron.rotated {
    transform: rotate(180deg);
  }

  .pricing-section {
    padding: 1.25rem 1.5rem;
    border-bottom: 1px solid var(--border-color, #e5e7eb);
  }

  .pricing-section:last-of-type {
    border-bottom: none;
  }

  .section-title {
    margin: 0 0 1rem;
    font-size: 0.875rem;
    font-weight: 600;
    text-transform: uppercase;
    color: var(--text-secondary, #6b7280);
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .toggle-discounts {
    font-size: 0.75rem;
    color: var(--primary-color, #3b82f6);
    background: none;
    border: none;
    cursor: pointer;
    text-transform: none;
  }

  .line-item {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 0.75rem;
    font-size: 0.875rem;
  }

  .line-item:last-child {
    margin-bottom: 0;
  }

  .line-item.subtotal {
    padding-top: 0.75rem;
    border-top: 1px solid var(--border-color, #e5e7eb);
    font-weight: 600;
  }

  .line-item.discount {
    color: var(--success-color, #10b981);
  }

  .line-item.small {
    font-size: 0.75rem;
    color: var(--text-secondary, #6b7280);
  }

  .item-details {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 0.125rem;
  }

  .item-name {
    color: var(--text-primary, #111827);
  }

  .item-quantity,
  .item-description {
    font-size: 0.75rem;
    color: var(--text-secondary, #6b7280);
  }

  .item-price {
    font-weight: 500;
    white-space: nowrap;
    margin-left: 1rem;
  }

  .discount-amount {
    color: var(--success-color, #10b981);
  }

  .option-group {
    margin-bottom: 1rem;
    padding-bottom: 1rem;
    border-bottom: 1px dashed var(--border-color, #e5e7eb);
  }

  .option-group:last-child {
    margin-bottom: 0;
    padding-bottom: 0;
    border-bottom: none;
  }

  .volume-tiers {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 0.75rem;
  }

  .tier-item {
    padding: 0.75rem;
    background: var(--bg-tertiary, #f9fafb);
    border: 1px solid var(--border-color, #e5e7eb);
    border-radius: 6px;
    text-align: center;
    transition: all 0.2s;
  }

  .tier-item.active {
    background: var(--primary-bg, #eff6ff);
    border-color: var(--primary-color, #3b82f6);
  }

  .tier-range {
    font-size: 0.875rem;
    font-weight: 600;
    color: var(--text-primary, #111827);
    margin-bottom: 0.25rem;
  }

  .tier-discount {
    font-size: 0.75rem;
    color: var(--text-secondary, #6b7280);
  }

  .active-badge {
    display: inline-block;
    padding: 0.125rem 0.5rem;
    background: var(--primary-color, #3b82f6);
    color: white;
    border-radius: 999px;
    font-size: 0.625rem;
    font-weight: 600;
    margin-left: 0.25rem;
  }

  .breakdown-items {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .pricing-footer {
    padding: 1.5rem;
    background: var(--bg-tertiary, #f3f4f6);
  }

  .final-total {
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 1.5rem;
    font-weight: 700;
    color: var(--text-primary, #111827);
  }

  .currency-note {
    margin-top: 0.5rem;
    font-size: 0.75rem;
    color: var(--text-secondary, #6b7280);
    text-align: right;
  }

  @media (max-width: 640px) {
    .pricing-section {
      padding: 1rem;
    }

    .volume-tiers {
      grid-template-columns: 1fr;
    }
  }
</style>
